#!/usr/bin/env python3
import os
import sys
import _fake as f

a = sys.argv[1:]
if a[:1] == ["compile"]:
    # The GDM helper compiles its own database file; that is a pure file operation, so the real tool runs.
    os.execv("/usr/bin/dconf", ["/usr/bin/dconf"] + a)
f.log("dconf " + " ".join(a))
store = f.load()
if a[:1] == ["read"] and len(a) == 2:
    if a[1] in store:
        print(store[a[1]])
elif a[:1] == ["write"] and len(a) == 3:
    store[a[1]] = a[2]
    f.save(store)
elif a[:1] == ["reset"]:
    store.pop(a[-1], None)
    f.save(store)
else:
    f.fail("unsupported dconf call: " + " ".join(a))
