#!/usr/bin/env python3
import json
import sys
import _fake as f

a = [x for x in sys.argv[1:] if x != "--user"]
f.log("systemctl --user " + " ".join(a))
p = f.FAKE / "services.json"
svc = json.loads(p.read_text()) if p.exists() else {}
cmd, rest = (a[0], a[1:]) if a else ("", [])
names = [x for x in rest if not x.startswith("-")]
if cmd in ("enable", "disable"):
    for n in names:
        svc[n] = cmd == "enable" and "--now" in rest
    p.write_text(json.dumps(svc))
elif cmd == "is-active":
    sys.exit(0 if svc.get(names[0]) else 3)
elif cmd == "daemon-reload":
    pass
else:
    f.fail("unsupported systemctl call: " + " ".join(a))
