# Symbolic icons of applications (Files, Settings, players...): GNOME icon name -> Material Symbols (style chosen in
# build.py). Outline by default (Material 3 toolbar style); "!" = filled variant (fill1); "^" = flipped
# vertically; "%" = rotated a quarter turn.
# Names already present in map.py (top bar) keep their map.py version.
A = {}
def a(ctx, names, ms):
    for n in names.split(): A[n + '-symbolic'] = (ctx, ms)

# ---- actions
a('actions', 'action-unavailable', 'block')
a('actions', 'address-book-new contact-new', 'person_add')
a('actions', 'application-exit system-log-out', 'logout')
a('actions', 'appointment-new', 'calendar_add_on')
a('actions', 'bookmark-new', 'bookmark_add')
a('actions', 'call-start', 'call')
a('actions', 'call-stop', 'call_end')
a('actions', 'camera-switch', 'cameraswitch')
a('actions', 'chat-message-new', 'add_comment')
a('actions', 'color-select', 'palette')
a('actions', 'document-edit', 'edit')
a('actions', 'document-new', 'note_add')
a('actions', 'document-open-recent', 'history')
a('actions', 'document-open', 'folder_open')
a('actions', 'document-page-setup', 'page_info')
a('actions', 'document-print-preview', 'preview')
a('actions', 'document-print image-print', 'print')
a('actions', 'document-properties help-about info-outline', 'info')
a('actions', 'document-revert', 'restore_page')
a('actions', 'document-save-as', 'save_as')
a('actions', 'document-save', 'save')
a('actions', 'document-send mail-send send-to', 'send')
a('actions', 'edit-clear-all', 'clear_all')
a('actions', 'edit-clear', 'backspace')
a('actions', 'edit-copy', 'content_copy')
a('actions', 'edit-cut cut cut-large', 'content_cut')
a('actions', 'edit-delete', 'delete')
a('actions', 'edit-find-replace', 'find_replace')
a('actions', 'edit-find system-search', 'search')
a('actions', 'edit-paste', 'content_paste')
a('actions', 'edit-redo', 'redo')
a('actions', 'edit-undo', 'undo')
a('actions', 'edit-select-all', 'select_all')
a('actions', 'edit-select', 'select')
a('actions', 'error-correct tools-check-spelling', 'spellcheck')
a('actions', 'folder-new', 'create_new_folder')
a('actions', 'font-select', 'font_download')
a('actions', 'format-indent-less', 'format_indent_decrease')
a('actions', 'format-indent-more', 'format_indent_increase')
a('actions', 'format-justify-center', 'format_align_center')
a('actions', 'format-justify-fill', 'format_align_justify')
a('actions', 'format-justify-left', 'format_align_left')
a('actions', 'format-justify-right', 'format_align_right')
a('actions', 'format-text-bold', 'format_bold')
a('actions', 'format-text-italic', 'format_italic')
a('actions', 'format-text-strikethrough', 'format_strikethrough')
a('actions', 'format-text-underline', 'format_underlined')
a('actions', 'format-text-direction format-text-direction-ltr', 'format_textdirection_l_to_r')
a('actions', 'format-text-direction-rtl', 'format_textdirection_r_to_l')
a('actions', 'format-text-plaintext insert-text', 'text_fields')
a('actions', 'format-text-rich rich-text', 'text_format')
a('actions', 'go-bottom', 'vertical_align_bottom')
a('actions', 'go-top', 'vertical_align_top')
a('actions', 'go-down', 'arrow_downward')
a('actions', 'go-up', 'arrow_upward')
a('actions', 'go-first', 'first_page')
a('actions', 'go-last', 'last_page')
a('actions', 'go-home', 'home')
a('actions', 'go-jump', 'arrow_outward')
a('actions', 'arrow-next', 'arrow_forward')
a('actions', 'insert-image', 'add_photo_alternate')
a('actions', 'insert-link', 'add_link')
a('actions', 'insert-object', 'add_box')
a('actions', 'list-add value-increase', 'add')
a('actions', 'list-remove value-decrease', 'remove')
a('actions', 'list-remove-all', 'delete_sweep')
a('actions', 'mail-forward', 'forward')
a('actions', 'mail-mark-important', 'label_important')
a('actions', 'mail-mark-junk', 'report')
a('actions', 'mail-mark-notjunk', 'mark_email_read')
a('actions', 'mail-message-new', 'edit_square')
a('actions', 'mail-reply-all', 'reply_all')
a('actions', 'mail-reply-sender', 'reply')
a('actions', 'mail-send-receive', 'sync')
a('actions', 'mark-location', 'add_location')
a('actions', 'media-eject', 'eject')
a('actions', 'media-playback-pause', '!pause')
a('actions', 'media-playback-start', '!play_arrow')
a('actions', 'media-playback-stop', '!stop')
a('actions', 'media-seek-backward', '!fast_rewind')
a('actions', 'media-seek-forward', '!fast_forward')
a('actions', 'media-skip-backward', '!skip_previous')
a('actions', 'media-skip-forward', '!skip_next')
a('actions', 'media-view-subtitles', 'subtitles')
a('actions', 'object-flip-horizontal view-mirror', 'flip')
a('actions', 'object-flip-vertical', '%flip')
a('actions', 'object-rotate-left', 'rotate_left')
a('actions', 'object-rotate-right', 'rotate_right')
a('actions', 'object-select', 'check')
a('actions', 'open-menu', 'menu')
a('actions', 'process-stop cancel-operation file-operation-cancelled', 'cancel')
a('actions', 'file-operation-finished', 'check_circle')
a('actions', 'selection-mode', 'checklist')
a('actions', 'sidebar-show', 'left_panel_open')
a('actions', 'sidebar-show-right', 'right_panel_open')
a('actions', 'star-new', 'star')
a('actions', 'system-reboot', 'restart_alt')
a('actions', 'system-run', 'play_circle')
a('actions', 'system-switch-user', 'switch_account')
a('actions', 'tab-new', 'tab')
a('actions', 'view-app-grid', 'apps')
# Dash to Dock "Show applications" button (view-app-grid-<session mode>-symbolic, an icon specific to the Shell):
# grid_view
a('actions', 'view-app-grid-user', 'grid_view')
# Glyph size within its frame, per icon (1 = common footprint): grid_view fills the dock tile, so it is halved.
SCALE = {'view-app-grid-user-symbolic': 0.5}
a('actions', 'view-conceal', 'visibility_off')
a('actions', 'view-reveal', 'visibility')
a('actions', 'view-continuous', 'view_agenda')
a('actions', 'view-dual', 'view_column_2')
a('actions', 'view-paged', 'auto_stories')
a('actions', 'view-fullscreen', 'fullscreen')
a('actions', 'view-restore', 'fullscreen_exit')
a('actions', 'view-grid', 'grid_view')
a('actions', 'view-list', 'list')
a('actions', 'view-list-bullet', 'format_list_bulleted')
a('actions', 'view-list-ordered', 'format_list_numbered')
a('actions', 'view-more-horizontal', 'more_horiz')
a('actions', 'view-more', 'more_vert')
a('actions', 'view-pin', 'keep')
a('actions', 'view-refresh', 'refresh')
a('actions', 'view-sort-descending', 'sort')
a('actions', 'view-sort-ascending', '^sort')
a('actions', 'zoom-fit-best', 'fit_screen')
a('actions', 'zoom-in', 'zoom_in')
a('actions', 'zoom-out', 'zoom_out')
a('actions', 'zoom-original', 'fit_page')
# Nautilus-specific icons (otherwise Nautilus' own, Adwaita style)
a('actions', 'emblem-readonly', 'edit_off')
a('actions', 'emblem-symbolic-link', 'link')
a('actions', 'emblem-unwriteable', 'lock')
a('actions', 'external-link window-new', 'open_in_new')
a('actions', 'funnel-outline nautilus-search-filters', 'filter_alt')
a('actions', 'nautilus-file-chooser-options', 'tune')
a('actions', 'nautilus-folder-search', 'manage_search')
a('actions', 'network-computer', 'computer')
a('actions', 'paper', 'description')
a('actions', 'quotation', 'format_quote')
a('actions', 'remove-custom-icon', 'hide_image')

# ---- places (Nautilus sidebar)
a('places', 'folder inode-directory system-file-manager', 'folder')
a('places', 'folder-documents', 'description')
a('places', 'folder-download', 'download')
a('places', 'folder-drag-accept', 'drive_file_move')
a('places', 'folder-music', 'music_note')
a('places', 'folder-pictures', 'image')
a('places', 'folder-projects', 'folder_code')
a('places', 'folder-publicshare', 'folder_shared')
a('places', 'folder-remote', 'cloud')
a('places', 'folder-saved-search', 'saved_search')
a('places', 'folder-templates', 'note_stack')
a('places', 'folder-videos', 'movie')
a('places', 'network-server', 'dns')
a('places', 'start-here', 'apps')
a('places', 'user-bookmarks', 'bookmark')
a('places', 'user-desktop', 'desktop_windows')
a('places', 'user-home', 'home')
a('places', 'user-trash user-trash-full', 'delete')

# ---- devices (volumes, hardware)
a('devices', 'ac-adapter gnome-power-manager uninterruptible-power-supply', 'power')
a('devices', 'audio-card', 'graphic_eq')
a('devices', 'auth-face', 'face')
a('devices', 'auth-fingerprint', 'fingerprint')
a('devices', 'auth-sim', 'sim_card')
a('devices', 'auth-smartcard', 'credit_card')
a('devices', 'camera-photo', 'photo_camera')
a('devices', 'camera-video', 'videocam')
a('devices', 'colorimeter-colorhug', 'colorize')
a('devices', 'computer-apple-ipad', 'tablet_mac')
a('devices', 'display-projector', 'co_present')
a('devices', 'drive-harddisk drive-harddisk-solidstate drive-harddisk-system drive-harddisk-ieee1394', 'hard_drive')
a('devices', 'drive-harddisk-usb drive-removable-media media-removable', 'usb')
a('devices', 'drive-multidisk', 'storage')
a('devices', 'drive-optical media-optical media-optical-bd media-optical-cd media-optical-cd-audio media-optical-dvd', 'album')
a('devices', 'input-dialpad', 'dialpad')
a('devices', 'input-gaming', 'sports_esports')
a('devices', 'input-mouse', 'mouse')
a('devices', 'input-tablet', 'stylus')
a('devices', 'input-touchpad', 'touch_app')
a('devices', 'media-flash', 'sd_card')
a('devices', 'media-floppy', 'save')
a('devices', 'media-tape', 'voicemail')
a('devices', 'media-zip', 'folder_zip')
a('devices', 'modem', 'router')
a('devices', 'multimedia-player', 'speaker')
a('devices', 'multimedia-player-apple-ipod-touch pda phone-apple-iphone', 'smartphone')
a('devices', 'phone-old', 'call')
a('devices', 'printer printer-network', 'print')
a('devices', 'scanner', 'scanner')
a('devices', 'video-display video-single-display', 'monitor')
a('devices', 'video-joined-displays', 'tv_displays')

# ---- mimetypes
a('mimetypes', 'application-certificate', 'verified')
a('mimetypes', 'application-rss+xml', 'rss_feed')
a('mimetypes', 'application-x-addon', 'extension')
a('mimetypes', 'application-x-appliance', 'inventory_2')
a('mimetypes', 'application-x-executable utilities-terminal', 'terminal')
a('mimetypes', 'application-x-firmware', 'memory')
a('mimetypes', 'application-x-sharedlib', 'data_object')
a('mimetypes', 'audio-x-generic', 'music_note')
a('mimetypes', 'font-x-generic preferences-desktop-font', 'text_fields')
a('mimetypes', 'image-x-generic', 'image')
a('mimetypes', 'package-x-generic', 'package_2')
a('mimetypes', 'text-x-generic', 'description')
a('mimetypes', 'video-x-generic', 'movie')
a('mimetypes', 'x-office-address-book', 'contacts')
a('mimetypes', 'x-office-calendar', 'calendar_month')
a('mimetypes', 'x-office-document', 'article')
a('mimetypes', 'x-office-drawing', 'draw')
a('mimetypes', 'x-office-presentation', 'slideshow')
a('mimetypes', 'x-office-spreadsheet', 'table')

# ---- categories
a('categories', 'applications-engineering', 'engineering')
a('categories', 'applications-games', 'sports_esports')
a('categories', 'applications-graphics', 'brush')
a('categories', 'applications-multimedia', 'perm_media')
a('categories', 'applications-science', 'science')
a('categories', 'applications-system', 'settings_applications')
a('categories', 'applications-utilities', 'build')
a('categories', 'emoji-activities', 'sports_soccer')
a('categories', 'emoji-body', 'front_hand')
a('categories', 'emoji-flags', 'flag')
a('categories', 'emoji-food', 'restaurant')
a('categories', 'emoji-nature', 'pets')
a('categories', 'emoji-objects', 'lightbulb')
a('categories', 'emoji-people', 'mood')
a('categories', 'emoji-recent', 'schedule')
a('categories', 'emoji-symbols accessories-character-map', 'emoji_symbols')
a('categories', 'emoji-travel', 'directions_car')
a('categories', 'preferences-other', 'category')
a('categories', 'system-help help-browser help-contents dialog-question', 'help')

# ---- emotes
a('emotes', 'emote-love', 'favorite')
a('emotes', 'face-angel', 'sentiment_calm')
a('emotes', 'face-angry', 'sentiment_extremely_dissatisfied')
a('emotes', 'face-confused face-embarrassed', 'sentiment_stressed')
a('emotes', 'face-raspberry face-surprise', 'sentiment_excited')
a('emotes', 'face-crying', 'sentiment_very_dissatisfied')
a('emotes', 'face-devilish', 'sentiment_frustrated')
a('emotes', 'face-glasses face-cool', 'face')
a('emotes', 'face-kiss face-smirk', 'sentiment_content')
a('emotes', 'face-laugh face-smile-big', 'sentiment_very_satisfied')
a('emotes', 'face-monkey', 'pets')
a('emotes', 'face-plain face-shutmouth face-uncertain', 'sentiment_neutral')
a('emotes', 'face-sad', 'sentiment_dissatisfied')
a('emotes', 'face-sick', 'sick')
a('emotes', 'face-smile', 'sentiment_satisfied')
a('emotes', 'face-tired face-yawn', 'bedtime')
a('emotes', 'face-wink', 'mood')
a('emotes', 'face-worried', 'sentiment_worried')

# ---- apps (old "legacy" names, used by Settings and others)
a('apps', 'accessories-calculator', 'calculate')
a('apps', 'accessories-dictionary', 'menu_book')
a('apps', 'accessories-text-editor text-editor', 'edit_note')
a('apps', 'emblem-important dialog-error', 'error')
a('apps', 'goa-panel', 'account_circle')
a('apps', 'help-faq', 'quiz')
a('apps', 'multimedia-volume-control', 'volume_up')
a('apps', 'preferences-color preferences-desktop-appearance', 'palette')
a('apps', 'preferences-desktop-accessibility', 'accessibility_new')
a('apps', 'preferences-desktop-apps', 'apps')
a('apps', 'preferences-desktop-display', 'monitor')
a('apps', 'preferences-desktop-keyboard-shortcuts', 'keyboard_command_key')
a('apps', 'preferences-desktop-keyboard', 'keyboard')
a('apps', 'preferences-desktop-locale web-browser', 'language')
a('apps', 'preferences-desktop-multitasking', 'select_window')
a('apps', 'preferences-desktop-remote-desktop', 'screen_share')
a('apps', 'preferences-desktop-screensaver', 'screen_lock_landscape')
a('apps', 'preferences-desktop-wallpaper', 'wallpaper')
a('apps', 'preferences-system-details dialog-information', 'info')
a('apps', 'preferences-system-devices', 'devices')
a('apps', 'preferences-system-network-proxy', 'public')
a('apps', 'preferences-system-network', 'lan')
a('apps', 'preferences-system-notifications', 'notifications')
a('apps', 'preferences-system-parental-controls', 'family_restroom')
a('apps', 'preferences-system-privacy', 'privacy_tip')
a('apps', 'preferences-system-search', 'search')
a('apps', 'preferences-system-sharing', 'share')
a('apps', 'preferences-system-time', 'schedule')
a('apps', 'system-software-install', 'install_desktop')
a('apps', 'system-users', 'group')
a('apps', 'user-info avatar-default', 'account_circle')

# ---- status (inside applications; top bar ones are in map.py)
a('status', 'alarm', 'alarm')
a('status', 'appointment-missed task-past-due', 'event_busy')
a('status', 'appointment-soon task-due', 'event_upcoming')
a('status', 'auth-sim-locked', 'sim_card')
a('status', 'auth-sim-missing', 'no_sim')
a('status', 'call-incoming', 'call_received')
a('status', 'call-missed', 'call_missed')
a('status', 'call-outgoing', 'call_made')
a('status', 'changes-allow', 'lock_open')
a('status', 'changes-prevent channel-secure', 'lock')
a('status', 'channel-insecure', 'no_encryption')
a('status', 'computer-fail', 'report')
a('status', 'content-loading image-loading', 'hourglass_empty')
a('status', 'daytime-sunrise daytime-sunset', 'wb_twilight')
a('status', 'dialog-password', 'password')
a('status', 'dialog-warning printer-warning weather-severe-alert', 'warning')
a('status', 'folder-open folder-visiting', 'folder_open')
a('status', 'image-missing', 'broken_image')
a('status', 'mail-attachment', 'attach_file')
a('status', 'mail-read', 'drafts')
a('status', 'mail-replied', 'reply')
a('status', 'mail-unread', 'mail')
a('status', 'media-playlist-consecutive', 'playlist_play')
a('status', 'media-playlist-repeat-song', 'repeat_one')
a('status', 'media-playlist-repeat', 'repeat')
a('status', 'media-playlist-shuffle', 'shuffle')
a('status', 'non-starred', 'star')
a('status', 'starred', '!star')
a('status', 'semi-starred', 'star_half')
a('status', 'orientation-landscape orientation-landscape-inverse', 'crop_landscape')
a('status', 'orientation-portrait-left orientation-portrait-right', 'crop_portrait')
a('status', 'printer-error', 'print_disabled')
a('status', 'printer-printing', 'print')
a('status', 'security-high', 'verified_user')
a('status', 'security-medium', 'gpp_maybe')
a('status', 'security-low', 'gpp_bad')
a('status', 'software-update-available', 'system_update')
a('status', 'software-update-urgent', 'new_releases')
a('status', 'touch-disabled touchpad-disabled', 'do_not_touch')
a('status', 'user-available', '!circle')
a('status', 'user-away user-idle', 'schedule')
a('status', 'user-busy', 'do_not_disturb_on')
a('status', 'user-invisible', 'visibility_off')
a('status', 'user-not-tracked', 'person_off')
a('status', 'user-offline', 'radio_button_unchecked')
a('status', 'user-status-pending', 'pending')
a('status', 'view-wrapped', 'wrap_text')
a('status', 'weather-clear', 'sunny')
a('status', 'weather-clear-night', 'bedtime')
a('status', 'weather-few-clouds', 'partly_cloudy_day')
a('status', 'weather-few-clouds-night', 'partly_cloudy_night')
a('status', 'weather-fog', 'foggy')
a('status', 'weather-overcast', 'cloud')
a('status', 'weather-showers weather-showers-scattered', 'rainy')
a('status', 'weather-snow', 'weather_snowy')
a('status', 'weather-storm', 'thunderstorm')
a('status', 'weather-tornado', 'tornado')
a('status', 'weather-windy', 'air')

# ---- ui
a('ui', 'pan-down', 'expand_more')
a('ui', 'pan-up', 'expand_less')
a('ui', 'list-drag-handle', 'drag_indicator')
