# shellcheck shell=bash
# Backup of everything the installer replaces or changes, in $STATE_DIR/backup/<timestamp>/:
#   files/<abs path>   pre-existing files and directories we moved out of the way
#   moved.list         their original paths
#   dconf.tsv          original dconf value of every key we set (empty value = key was unset)
#   restore.sh         generated, standalone: puts the files back and restores the dconf keys
# Requires common.sh and manifest.sh.

BACKUP_DIR=''
STATE_FILE=''

state_get() { # key -> value ('' when absent)
    [[ -f "$STATE_FILE" ]] || return 0
    sed -n "s/^$1=//p" "$STATE_FILE" | tail -n 1
}

state_set() { # key value
    ((DRY_RUN)) && return 0
    local tmp
    tmp="$(mktemp "$STATE_DIR/state.XXXXXX")"
    {
        if [[ -f "$STATE_FILE" ]]; then grep -v -- "^$1=" "$STATE_FILE" || [[ $? -eq 1 ]]; fi # 1 = no line left, not an error
        printf '%s=%s\n' "$1" "$2"
    } >"$tmp"
    mv -- "$tmp" "$STATE_FILE"
}

backup_init() {
    STATE_FILE="$STATE_DIR/state"
    local name
    name="$(state_get backup)"
    if [[ -n "$name" && -d "$STATE_DIR/backup/$name" ]]; then
        BACKUP_DIR="$STATE_DIR/backup/$name"
    else
        BACKUP_DIR=''
    fi
}

backup_dir_ensure() {
    [[ -n "$BACKUP_DIR" ]] && return 0
    local name
    name="$(date +%Y%m%d-%H%M%S)"
    BACKUP_DIR="$STATE_DIR/backup/$name"
    mkdir -p -- "$BACKUP_DIR/files"
    : >"$BACKUP_DIR/moved.list"
    : >"$BACKUP_DIR/dconf.tsv"
    state_set backup "$name"
}

backup_move() { # path: move something we do not own into the backup
    local p="$1"
    if ((DRY_RUN)); then msg_info "[dry-run] back up existing $p"; return 0; fi
    backup_dir_ensure
    local dest="$BACKUP_DIR/files/${p#/}"
    mkdir -p -- "$(dirname -- "$dest")"
    mv -- "$p" "$dest"
    printf '%s\n' "$p" >>"$BACKUP_DIR/moved.list"
    msg_info "backed up existing $p"
}

backup_dconf() { # dconf-path: remember the original value, once
    local path="$1" value
    ((DRY_RUN)) && return 0
    backup_dir_ensure
    awk -F'\t' -v p="$path" '$1 == p { found = 1 } END { exit !found }' "$BACKUP_DIR/dconf.tsv" && return 0
    value="$(dconf read "$path")"
    printf '%s\t%s\n' "$path" "$value" >>"$BACKUP_DIR/dconf.tsv"
}

# (Re)generate restore.sh from the recorded data.
# shellcheck disable=SC2016  # the generated script contains literal $-expressions
write_restore_script() {
    [[ -n "$BACKUP_DIR" ]] || return 0
    ((DRY_RUN)) && return 0
    local f="$BACKUP_DIR/restore.sh" path value p
    {
        printf '#!/usr/bin/env bash\n'
        printf '# Generated by m3e-gnome install.sh. Restores what the installer replaced or changed:\n'
        printf '# files moved aside are put back (skipped when something is already there), dconf keys get their\n'
        printf '# original value back. Run ./uninstall.sh to remove the installed files first.\n'
        printf 'set -u\nstatus=0\n'
        printf 'restore_moved() { # original-path backup-path\n'
        printf '    if [[ -e "$1" || -L "$1" ]]; then echo "skipped (already exists): $1" >&2; status=1; return; fi\n'
        printf '    mkdir -p -- "$(dirname -- "$1")" && mv -- "$2" "$1" && echo "restored: $1" || status=1\n}\n'
        printf 'here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
        while IFS= read -r p; do
            [[ -n "$p" ]] || continue
            printf 'restore_moved %q "$here"/files/%q\n' "$p" "${p#/}"
        done <"$BACKUP_DIR/moved.list"
        while IFS=$'\t' read -r path value; do
            [[ -n "$path" ]] || continue
            if [[ -z "$value" ]]; then
                printf 'dconf reset %q || status=1\n' "$path"
            else
                printf 'dconf write %q %q || status=1\n' "$path" "$value"
            fi
        done <"$BACKUP_DIR/dconf.tsv"
        printf 'exit "$status"\n'
    } >"$f"
    chmod 755 "$f"
}
