# shellcheck shell=bash
# Install steps for the visual assets: GTK/Shell base theme, icons, cursor, sounds, font.
# Requires common.sh, manifest.sh, fetch.sh, pins.sh; REPO_ROOT and the option variables set by install.sh.

step_gtk_theme() {
    msg_step "GTK 3/4 base theme (Material-Gnome)"
    fetch_git material-gnome "$MATGNOME_URL" "$MATGNOME_REV"
    # The base theme is GPL-3.0-or-later: it is fetched here, at install time, not shipped in this repository.
    put_tree "$SRC_DIR/material-gnome" "$THEMES_DIR/Material-Gnome" --exclude .git --exclude .github --exclude screenshots
    if ((DRY_RUN)); then
        msg_info "[dry-run] strip bold weights from the GTK 4 stylesheets"
    else
        # No bold anywhere. libadwaita imports this stylesheet at the same priority as no-bold-gtk4.css, whose
        # universal selector loses to the theme's class selectors: remove the weights at the source instead.
        sed -i -E 's/font-weight: *(bold|bolder|[6-9]00)/font-weight: normal/g' "$THEMES_DIR"/Material-Gnome/gtk-4.0/gtk*.css
        printf '%s\n' "$MATGNOME_REV" >"$THEMES_DIR/Material-Gnome/.m3e-rev"
    fi
    # The Shell theme is one stylesheet generated by matugen from the templates (see step_palette).
    mkdir_owned "$THEMES_DIR/M3E-Shell/gnome-shell"
}

step_icons() {
    msg_step "Icons: Papirus, Material-Symbols, Papirus-Symbolic"
    fetch_git papirus-icon-theme "$PAPIRUS_URL" "$PAPIRUS_REV"
    fetch_git papirus-folders "$FOLDERS_URL" "$FOLDERS_REV"
    local t
    for t in Papirus Papirus-Dark; do
        put_tree "$SRC_DIR/papirus-icon-theme/$t" "$ICONS_DIR/$t"
    done
    put_file "$SRC_DIR/papirus-folders/papirus-folders" "$BIN_DIR/papirus-folders" 755
    # Hand-built symbolic theme (top bar, windows, applications) + links to the coloured folders of Papirus-Dark.
    put_tree "$REPO_ROOT/theme/icons/Material-Symbols" "$ICONS_DIR/Material-Symbols"
    # Material-Symbols falls back to the symbolic icons of Papirus only (not all of Papirus: saves ~1 s per app start).
    claim_tree "$ICONS_DIR/Papirus-Symbolic"
    run python3 "$REPO_ROOT/tools/papirus-symbolic.py" "$ICONS_DIR" >/dev/null
    if have gtk-update-icon-cache; then
        run gtk-update-icon-cache -q -f "$ICONS_DIR/Material-Symbols"
    else
        msg_warn "gtk-update-icon-cache not found: Material-Symbols has no icon cache, so GTK apps start slower"
    fi
}

step_cursor() {
    msg_step "Cursor: Googlebook ($CURSOR_STYLE)"
    local theme=Googlebook
    [[ "$CURSOR_STYLE" == white ]] && theme=Googlebook-White
    claim_tree "$ICONS_DIR/$theme"
    run python3 "$REPO_ROOT/tools/googlebook-cursors/build.py" "$CURSOR_STYLE" --icons-dir "$ICONS_DIR" >/dev/null
    # X11 and legacy toolkits read ~/.icons/default.
    put_text "$HOME/.icons/default/index.theme" 644 <<<"[Icon Theme]
Inherits=$theme"
}

step_sounds() {
    msg_step "Sound theme: Materia"
    fetch_git materia-sound-theme "$MATERIA_URL" "$MATERIA_REV"
    if ((DRY_RUN)); then msg_info "[dry-run] meson install into a staging directory, then copy to $DATA_HOME/sounds/Materia"; return 0; fi
    local tmp
    make_tmp; tmp="$REPLY"
    meson setup "$tmp/build" "$SRC_DIR/materia-sound-theme" --prefix=/usr >/dev/null
    meson install -C "$tmp/build" --destdir "$tmp/stage" >/dev/null
    put_tree "$tmp/stage/usr/share/sounds/Materia" "$DATA_HOME/sounds/Materia"
}

step_font() {
    msg_step "Font: Google Sans Flex (SIL OFL 1.1)"
    local dir="$DATA_HOME/fonts/GoogleSansFlex" tmp
    if ((DRY_RUN)); then msg_info "[dry-run] download Google Sans Flex into $dir"; return 0; fi
    make_tmp; tmp="$REPLY"
    download_verified "$GSF_BASE/$GSF_URL_NAME" "$tmp/font.ttf" "$GSF_SHA256"
    download_verified "$GSF_BASE/OFL.txt" "$tmp/OFL.txt" "$GSF_OFL_SHA256"
    put_file "$tmp/font.ttf" "$dir/$GSF_FILE" 644
    put_file "$tmp/OFL.txt" "$dir/OFL.txt" 644
    run fc-cache -f "$dir"
}
