#!/usr/bin/env bash
# Reproducible README screenshots: dark and light sessions of the theme in a nested, headless GNOME Shell.
#
# Usage: capture.sh [--out DIR] [--modes dark,light] [--wallpaper NAME] [--scenarios all|apps|shell] [--stock-gtk]
#   --out DIR        working directory (default: a new directory under ${M3E_BENCH_OUT:-<repo>/dev/out}/screenshots)
#   --modes          default dark,light
#   --stock-gtk      no GTK user stylesheet: the stock libadwaita look, to tell theme defects from stock behaviour
#   --wallpaper      dunes (default), ocean, dusk or forest: generated by wallpapers.py; the palette is derived from it
# Output: <out>/<mode>/*.png (raw 1920x1080 captures). compose.py turns them into the optimized files of screenshots/.
# Privacy: the session runs with a fake HOME (<out>/<mode>/home/demo), a generated wallpaper, a PRIVATE system bus
# (sysbus.py: fake Wi-Fi, Bluetooth and battery; the real NetworkManager/BlueZ/UPower are never reached), a private
# audio server (audio.py: one fake output) and a private session bus; nothing of the real home, dconf or ~/.config is read by the session or written. Only PIDs started here
# are signalled. nested.sh (m3e-gnome-extensions) owns the other guards; its dconf guard looks at $HOME, which is the fake
# one here, so this script checks the REAL dconf database itself.
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
# shellcheck source=../m3e-bench/nested-launcher.sh
source "$REPO/dev/m3e-bench/nested-launcher.sh" || exit 2
PY="${M3E_SHOTS_PYTHON:-$HERE/.venv/bin/python}"
OUT=''; MODES='dark,light'; WALLPAPER='dunes'; SCENARIOS='all'; STAGE_ARGS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --out) OUT="${2:?}"; shift 2 ;;
        --modes) MODES="${2:?}"; shift 2 ;;
        --wallpaper) WALLPAPER="${2:?}"; shift 2 ;;
        --scenarios) SCENARIOS="${2:?}"; shift 2 ;;
        --stock-gtk) STAGE_ARGS+=(--stock-gtk); shift ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done
[[ "$MODES" =~ ^(dark|light)(,(dark|light))*$ && "$SCENARIOS" =~ ^[a-z0-9,]+$ && "$WALLPAPER" =~ ^[a-z]+$ ]] ||
    { echo "invalid arguments" >&2; exit 2; }
[[ -x "$PY" ]] || { echo "no interpreter at $PY: run $HERE/setup.sh first" >&2; exit 2; }
: "${XDG_RUNTIME_DIR:?XDG_RUNTIME_DIR is not set}"
[[ -n "$OUT" ]] || OUT="${M3E_BENCH_OUT:-$REPO/dev/out}/screenshots/$(date +%Y%m%d-%H%M%S)"
mkdir -p "$OUT" && OUT="$(cd "$OUT" && pwd)" || exit 2

REAL_DCONF="${XDG_CONFIG_HOME:-$HOME/.config}/dconf/user"
dconf_state() { stat -c '%y %s' "$REAL_DCONF" 2>/dev/null || echo absent; }
DCONF_BEFORE="$(dconf_state)"

SYSBUS_PID=''; AUDIO_PID=''
cleanup() {
    local pid
    for pid in "$SYSBUS_PID" "$AUDIO_PID"; do
        [[ -n "$pid" ]] && kill "$pid" 2>/dev/null && wait "$pid" 2>/dev/null
    done
}
trap cleanup EXIT
"$PY" "$HERE/sysbus.py" --dir "$OUT/sysbus" >"$OUT/sysbus.log" 2>&1 &
SYSBUS_PID=$!
for _ in $(seq 1 100); do [[ -s "$OUT/sysbus/address" ]] && break; sleep 0.2; done
[[ -s "$OUT/sysbus/address" ]] || { echo "private system bus did not start (see $OUT/sysbus.log)" >&2; exit 1; }
SYSTEM_BUS="$(cat "$OUT/sysbus/address")"
[[ "$SYSTEM_BUS" == "unix:path=$OUT/"* ]] || { echo "unexpected system bus address: $SYSTEM_BUS" >&2; exit 1; }

python3 "$HERE/audio.py" --dir "$OUT/audio" >"$OUT/audio.log" 2>&1 &
AUDIO_PID=$!
for _ in $(seq 1 100); do [[ -s "$OUT/audio/address" ]] && break; sleep 0.2; done
[[ -s "$OUT/audio/address" ]] || { echo "private audio server did not start (see $OUT/audio.log)" >&2; exit 1; }
PULSE="$(cat "$OUT/audio/address")"
[[ "$PULSE" == "unix:$OUT/"* ]] || { echo "unexpected pulse address: $PULSE" >&2; exit 1; }

status=0
IFS=',' read -ra MODE_LIST <<<"$MODES"
for MODE in "${MODE_LIST[@]}"; do
    DIR="$OUT/$MODE"
    "$PY" "$HERE/stage.py" --out "$DIR" --mode "$MODE" --wallpaper "$WALLPAPER" \
        --extensions-repo "$M3E_EXTENSIONS_REPO" ${STAGE_ARGS[@]+"${STAGE_ARGS[@]}"} || { echo "stage.py failed ($MODE)" >&2; exit 1; }
    STAGE="$DIR/stage"
    (
        # shellcheck disable=SC1091
        source "$DIR/env.sh"
        export DBUS_SYSTEM_BUS_ADDRESS="$SYSTEM_BUS" PULSE_SERVER="$PULSE" M3E_SHOTS_SCRIPTS="$HERE" M3E_SHOTS_PYTHON="$PY"
        enable=()
        for ext in "$STAGE"/ext/*/; do enable+=(--enable-ext "${ext%/}"); done
        bash "$NESTED_SH" --scenarios "$SCENARIOS" --out "$DIR" --locale en_US.UTF-8 \
            --extension "$STAGE/ext-shots" "${enable[@]}" --dconf-keyfile "$DIR/settings.keyfile"
    )
    code=$?
    [[ $code -ne 0 ]] && { echo "nested.sh ($MODE) exited with $code (see $DIR/shell.log)" >&2; status=1; }
done
if [[ "$(dconf_state)" != "$DCONF_BEFORE" ]]; then
    echo "the real dconf database changed during the run ($REAL_DCONF): please check (the real session may write too)" >&2
    status=1
fi
echo "output: $OUT"
exit $status
